### ISSUE TITLE
Morning session code review

### ISSUE THREAD

**Issue by stephenkati** [preciousbetine/microverse-portfolio#20]
Your project is looking good with nice use of **animations**.

However, there are some issues that need fixing:

1. **Card size** does not match figma UI design.
2. **Background color** in contact form section is not the right one according to the design. It is causing very low contrast (3.99:1). It should be above (4.5:1).
3. The **button** in desktop view should be at the middle.

Cheers and happy coding.

**Comment by preciousuwhubetine** [comment]
Thanks! The issues have been fixed.
