### ISSUE TITLE
Debugging Required

### ISSUE THREAD

**Issue by vangelif** [preciousbetine/microverse-portfolio#21]
https://github.com/preciousbetine/microverse-portfolio/blob/d54f0dbc15390364d943f16414b62bd04e2bf78a/script.js#L190-L192

- Kindly review the id being used here. Please check if there are any typos or any missing '-'. 

https://github.com/preciousbetine/microverse-portfolio/blob/d54f0dbc15390364d943f16414b62bd04e2bf78a/script.js#L216-L220

- Please recheck for typos in your event handlers. 

https://github.com/preciousbetine/microverse-portfolio/blob/d54f0dbc15390364d943f16414b62bd04e2bf78a/script.js#L192

- Kindly amend the .display here to 'none'.

**Comment by preciousuwhubetine** [comment]
The issues have been fixed. Thanks for helping me spot them.
